require: rubocop-rspec

AllCops:
  DisplayCopNames: true

Metric/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/qa/ldf/spec/**/*'

# Class variables are fine. We want the "nasty" behavior described by rubocop 
# in some cases.
# https://github.com/bbatsov/ruby-style-guide/blob/master/README.md#no-class-vars
Style/ClassVars:
  Enabled: false

# we accept `expect(subject).to receive`
RSpec/MessageSpies:
  Enabled: false

# we accept specs in fakes, mocks, &c...
RSpec/FilePath:
  Exclude:
    - 'spec/contracts/**/*'
    - 'spec/support/**/*'
    - 'spec/qa/ldf/authorities/**/*'
    - 'spec/qa/ldf/models/**/*'

# we allow non-Class describes for integration
RSpec/DescribeClass:  
  Exclude:
    - 'spec/integration/**/*'