require: rubocop-rspec

AllCops:
  DisplayCopNames: true

Metric/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/qa/ldf/spec/**/*'

# we accept `expect(subject).to receive`
RSpec/MessageSpies:
  Enabled: false

# we accept specs in fakes, mocks, &c...
RSpec/FilePath:
  Exclude:
    - 'spec/contracts/**/*'
    - 'spec/support/**/*'
    - 'spec/qa/ldf/authorities/**/*'
